### ISSUE TITLE
island 사이에 에러 객체가 전달되지 않음

### ISSUE THREAD

**Issue by heycalmdown** [spearhead-ea/island#1]
예전에 msgpack -> JSON.stringify로 바꾸면서 아일랜드 사이에 에러 객체가 전달되지 않게되었음
- [ ] AbstractError에 toJSON 추가
- [ ] Error를 위한 reviver 작성

**Comment by tedlines** [comment]
https://github.com/spearhead-ea/island/blob/3eabc33857211cfb0c419233019ae377c1c788f6/src/services/rpc-service.ts#L77
https://github.com/spearhead-ea/island/blob/3eabc33857211cfb0c419233019ae377c1c788f6/src/services/rpc-service.ts#L382

잘 전달되고 있습니다. ㅎㅎ
