### ISSUE TITLE
validate.NumberOrQuery needed

### ISSUE THREAD

**Issue by heycalmdown** [spearhead-ea/island#20]
리소스를 요청할 때 쿼리 파라미터가 숫자일 때, 숫자 대신 다음과 같은 쿼리를 쓰는 일도 흔합니다.

```
?speed.$gte=90
```

Query 형태로 쓸 수 있게 하면 좋겠습니다.

**Comment by wokim** [comment]
NumberOrQuery 는 우리쪽에서 만든겁니다!
