### ISSUE TITLE
@admin need to be less opinionated

### ISSUE THREAD

**Issue by heycalmdown** [spearhead-ea/island#23]
Current behavior of `@admin` is adding prefix `/admin` in front of the specified URI. This is useful to group these APIs by prefix, but seems having too hard limit.

It'll be nice if it allows developers to override the prefix.

## AS-IS

```typescript
// AS-IS
@admin
@endpoint('GET /admin/account/list')
getAccountList(req) {
  return [];
}

// TO-BE
@admin('/ops')
@endpoint('GET /ops/account/list')
getAccountList(req) {
  return [];
}
```

**Comment by heycalmdown** [comment]
or for saving few more strokes...

```typescript
admin.__prefix = '/ops';

@admin
@endpoint('GET /ops/account/list')
getAccountList(req) {
  return [];
}
```

**Comment by wokim** [comment]
Will following the examples be same?

``
@admin('/ops')
@endpoint('GET /ops/account/list')
getAccountList(req) {
  return [];
}
``

and

``
@admin('/ops')
@endpoint('GET /account/list')
getAccountList(req) {
  return [];
}
``

**Comment by heycalmdown** [comment]
Yes, as exactly same as current -

```typescript
@admin
@endpoint('GET /admin/account/list)
getAccountList(req) {
  return [];
}

@admin
@endpoint('GET /account/list)
getAccountList(req) {
  return [];
}
```

If it occurs confusing while designing URI by engineers, the feature can be eliminated.

**Comment by heycalmdown** [comment]
Now `@admin` doesn't adminize URI.
