### ISSUE TITLE
Code Climate should not lint files under typings

### ISSUE THREAD

**Issue by heycalmdown** [spearhead-ea/island#33]
[Issues](https://codeclimate.com/github/spearhead-ea/island/issues) on Code Climate shows lint issues including files under typings. They doesn't need to be checked.

**Comment by heycalmdown** [comment]
check this [config](https://codeclimate.com/repos/57fdf17fa6f8535380000bcd/analysis_config)

**Comment by tedlines** [comment]
https://github.com/spearhead-ea/island/commit/60befcba386f8f55d1bbc9e162e8b620db5dbf40
