### ISSUE TITLE
在 3rd party Module(Mongoose, redis etc)中 出现error时, 当error message发送到gateway_island时，Err信息中的msg是undefined。

### ISSUE THREAD

**Issue by tedlines** [spearhead-ea/island#41]
[--------|05:56:04|n] [RPC-WARNING] invalid correlationId
[e143e281|05:56:04|n] response error - undefined undefined.ETC.F0001 code: undefined.ETC.F0001, msg: undefined' /v2/tc/token undefined
[e143e281|05:56:04|d] ETCError: code: undefined.ETC.F0001, msg: undefined'
From previous event:
...

**Comment by yunghoy** [comment]
?!
